# Generated by Django 5.2 on 2025-04-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('now_showing', 'Now Showing'), ('upcoming', 'Upcoming')], default='now_showing', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='show_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='show_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
