# Generated by Django 5.2 on 2025-09-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_userprofile_user_delete_userprofileadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Horror', 'Horror')], default='Action', max_length=20),
        ),
    ]
